config/routes.rb
Rails.application.routes.draw do
  resources :bonus_points
  resources :sanctions
  resources :league_participants
  resources :race_participants
  devise_for :users
  resources :league_races
  resources :race_tracks
  resources :leagues
  resources :points_for_positions
  resources :score_systems

  root to: "leagues#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sanction.rb
class Sanction < ApplicationRecord
  belongs_to :league_race
  belongs_to :race_participant

  scope :from_league_race, -> (league_race) { where(league_race_id: league_race) }
end

app/controllers/sanctions_controller.rb
class SanctionsController < ApplicationController
  before_action :set_sanction, only: %i[ show edit update destroy ]

  # GET /sanctions or /sanctions.json
  def index
    @league_race = LeagueRace.find(params["league_race_id"])
    @sanctions = Sanction.from_league_race(@league_race.id)
  end

  # GET /sanctions/1 or /sanctions/1.json
  def show
  end

  # GET /sanctions/new
  def new
    @league_race = LeagueRace.find(params["league_race_id"])
    @sanction = Sanction.new
  end

  # GET /sanctions/1/edit
  def edit
  end

  # POST /sanctions or /sanctions.json
  def create
    @league_race = LeagueRace.find(params.dig(:sanction, :league_race_id))
    @sanction = Sanction.new(sanction_params)

    respond_to do |format|
      if @sanction.save
        UpdateLeagueParticipantScore.call(@league_race)
        UpdateLeagueParticipantPosition.call(@league_race)
        format.html { redirect_to sanctions_path(league_race_id: @league_race.id), notice: "Sanción creada correctamente" }
        format.json { render :show, status: :created, location: @sanction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sanction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sanctions/1 or /sanctions/1.json
  def update
    respond_to do |format|
      if @sanction.update(sanction_params)
        format.html { redirect_to sanction_url(@sanction), notice: "Sanction was successfully updated." }
        format.json { render :show, status: :ok, location: @sanction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sanction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sanctions/1 or /sanctions/1.json
  def destroy
    @sanction.destroy

    respond_to do |format|
      format.html { redirect_to sanctions_url, notice: "Sanction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sanction
      @sanction = Sanction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sanction_params
      params.require(:sanction).permit(:description, :video_url, :league_race_id, :race_participant_id, :penalized_points)
    end
end

app/helpers/sanctions_helper.rb
module SanctionsHelper
end

app/views/sanctions/_form.html.erb
<%= simple_form_for(@sanction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs col-md-8">
    <%= f.association :league_race,
                       as: :hidden,
                       input_html: { value: @league_race.id } %>
    
    <%= f.association :race_participant, collection: league_race_name_and_ids(@league_race.id),
                                         input_html: { class: 'form-control mb-2' } %>
    <%= f.input :description, input_html: { class: 'form-control mb-2' } %>
    <%= f.input :video_url, input_html: { class: 'form-control mb-2' } %>
    <%= f.input :penalized_points, input_html: { class: 'form-control mb-2' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Crear nueva sanción', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sanctions/edit.html.erb
<h1>Editing Sanction</h1>

<%= render 'form', sanction: @sanction %>

<%= link_to 'Show', @sanction %> |
<%= link_to 'Back', sanctions_path %>

app/views/sanctions/index.html.erb
<p id="notice"><%= notice %></p>

<div class='col-md-6'>
  <h1>Sanciones de la carrera: <strong><%= @league_race.capitalized_name %></strong></h1>
</div>

<%= link_to 'Crear nueva sanción', new_sanction_path(league_race_id: @league_race.id) %>

<div class='col-md-8'>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id de jugador</th>
        <th scope="col">Descripción</th>
        <th scope="col">Puntos de penalización</th>
        <th scope="col">Url de video</th>
      </tr>
    </thead>
    <tbody>
      <% @sanctions.each do |sanction| %>
        <tr>
          <td><%= sanction.race_participant.user.gamer_id %></td>
          <td><%= sanction.description %></td>
          <td>-<%= sanction.penalized_points %></td>
          <td><%= sanction.video_url %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<a href="<%= race_participants_path(league_race_id: @league_race.id) %>" class="btn btn-dark">Ver tabla de resultados de carrera</a>
<a href="<%= league_races_path(league_id: @league_race.league_id) %>" class="btn btn-dark">Volver a carreras de liga</a>
<a href="<%= league_participants_path(league_id: @league_race.league_id) %>" class="btn btn-dark">Ir a tabla general de la liga</a>

app/views/sanctions/new.html.erb
<div class='col-md-6'>
  <h1>Nueva sanción en <strong><%= @league_race.capitalized_name %></strong></h1>
</div>

<%= render 'form', sanction: @sanction %>

<%= link_to 'Volver a sanciones de carrera', sanctions_path(league_race_id: @league_race.id) %>

app/views/sanctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @sanction.description %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @sanction.video_url %>
</p>

<p>
  <strong>League race:</strong>
  <%= @sanction.league_race_id %>
</p>

<p>
  <strong>Race participant:</strong>
  <%= @sanction.race_participant_id %>
</p>

<%= link_to 'Edit', edit_sanction_path(@sanction) %> |
<%= link_to 'Back', sanctions_path %>