config/routes.rb
Rails.application.routes.draw do
  resources :bonus_points
  resources :sanctions
  resources :league_participants
  resources :race_participants
  devise_for :users
  resources :league_races
  resources :race_tracks
  resources :leagues
  resources :points_for_positions
  resources :score_systems

  root to: "leagues#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bonus_point.rb
class BonusPoint < ApplicationRecord
  belongs_to :league_race
  belongs_to :race_participant

  scope :from_league_race, -> (league_race) { where(league_race_id: league_race) }
end

app/controllers/bonus_points_controller.rb
class BonusPointsController < ApplicationController
  before_action :set_bonus_point, only: %i[ show edit update destroy ]

  # GET /bonus_points or /bonus_points.json
  def index
    @league_race = LeagueRace.find(params["league_race_id"])
    @bonus_points = BonusPoint.from_league_race(@league_race.id)
  end

  # GET /bonus_points/1 or /bonus_points/1.json
  def show
  end

  # GET /bonus_points/new
  def new
    @league_race = LeagueRace.find(params["league_race_id"])
    @bonus_point = BonusPoint.new
  end

  # GET /bonus_points/1/edit
  def edit
  end

  # POST /bonus_points or /bonus_points.json
  def create
    @bonus_point = BonusPoint.new(bonus_point_params)
    @league_race = LeagueRace.find(params.dig(:bonus_point, :league_race_id))

    respond_to do |format|
      if @bonus_point.save
        UpdateLeagueParticipantScore.call(@league_race)
        UpdateLeagueParticipantPosition.call(@league_race)
        format.html { redirect_to bonus_points_path(league_race_id: @league_race.id), notice: "Punto extra agregado correctamente" }
        format.json { render :show, status: :created, location: @bonus_point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bonus_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bonus_points/1 or /bonus_points/1.json
  def update
    respond_to do |format|
      if @bonus_point.update(bonus_point_params)
        format.html { redirect_to bonus_point_url(@bonus_point), notice: "Bonus point was successfully updated." }
        format.json { render :show, status: :ok, location: @bonus_point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bonus_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bonus_points/1 or /bonus_points/1.json
  def destroy
    @bonus_point.destroy

    respond_to do |format|
      format.html { redirect_to bonus_points_url, notice: "Bonus point was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bonus_point
      @bonus_point = BonusPoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bonus_point_params
      params.require(:bonus_point).permit(:description, :points, :league_race_id, :race_participant_id)
    end
end

app/helpers/bonus_points_helper.rb
module BonusPointsHelper
end

app/views/bonus_points/_form.html.erb
<%= simple_form_for(@bonus_point) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs col-md-8">
    <%= f.association :league_race,
                       as: :hidden,
                       input_html: { value: @league_race.id } %>
    
    <%= f.association :race_participant, collection: league_race_name_and_ids(@league_race.id),
                                         input_html: { class: 'form-control mb-2' } %>
    <%= f.input :description, input_html: { class: 'form-control mb-2' } %>
    <%= f.input :points, input_html: { class: 'form-control mb-2' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Agregar nuevo punto extra', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bonus_points/edit.html.erb
<h1>Editing Bonus Point</h1>

<%= render 'form', bonus_point: @bonus_point %>

<%= link_to 'Show', @bonus_point %> |
<%= link_to 'Back', bonus_points_path %>

app/views/bonus_points/index.html.erb
<p id="notice"><%= notice %></p>

<div class='col-md-6'>
  <h1>Puntos extra de la carrera: <strong><%= @league_race.capitalized_name %></strong></h1>
</div>

<%= link_to 'Agregar punto extra', new_bonus_point_path(league_race_id: @league_race.id) %>

<div class='col-md-8'>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id de jugador</th>
        <th scope="col">Descripción</th>
        <th scope="col">Puntos extra</th>
      </tr>
    </thead>
    <tbody>
      <% @bonus_points.each do |bonus_point| %>
        <tr>
          <td><%= bonus_point.race_participant.user.gamer_id %></td>
          <td><%= bonus_point.description %></td>
          <td><%= bonus_point.points %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<a href="<%= race_participants_path(league_race_id: @league_race.id) %>" class="btn btn-dark">Ver tabla de resultados de carrera</a>
<a href="<%= league_races_path(league_id: @league_race.league_id) %>" class="btn btn-dark">Volver a carreras de liga</a>
<a href="<%= league_participants_path(league_id: @league_race.league_id) %>" class="btn btn-dark">Ir a tabla general de la liga</a>

app/views/bonus_points/new.html.erb
<div class='col-md-6'>
  <h1>Nueva punto extra en <strong><%= @league_race.capitalized_name %></strong></h1>
</div>

<%= render 'form', bonus_point: @bonus_point %>

<%= link_to 'Volver a puntos extras de carrera', bonus_points_path(league_race_id: @league_race.id) %>

app/views/bonus_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @bonus_point.description %>
</p>

<p>
  <strong>Points:</strong>
  <%= @bonus_point.points %>
</p>

<p>
  <strong>League race:</strong>
  <%= @bonus_point.league_race_id %>
</p>

<p>
  <strong>Race participant:</strong>
  <%= @bonus_point.race_participant_id %>
</p>

<%= link_to 'Edit', edit_bonus_point_path(@bonus_point) %> |
<%= link_to 'Back', bonus_points_path %>