config/routes.rb
Rails.application.routes.draw do
  resources :bonus_points
  resources :sanctions
  resources :league_participants
  resources :race_participants
  devise_for :users
  resources :league_races
  resources :race_tracks
  resources :leagues
  resources :points_for_positions
  resources :score_systems

  root to: "leagues#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/league_race.rb
class LeagueRace < ApplicationRecord
  belongs_to :race_track
  belongs_to :league
  belongs_to :score_system
  has_many :race_participants
  has_many :sanctions
  has_many :bonus_points

  accepts_nested_attributes_for :race_participants, allow_destroy: true

  scope :from_league, -> (league) { where(league_id: league) }
end

app/controllers/league_races_controller.rb
class LeagueRacesController < ApplicationController
  before_action :set_league_race, only: %i[ show edit update destroy ]

  # GET /league_races or /league_races.json
  def index
    @league = League.find(params["league_id"])
    @league_races = LeagueRace.from_league(@league.id)
  end
  
  # GET /league_races/1 or /league_races/1.json
  def show
  end
  
  # GET /league_races/new
  def new
    @league = League.find(params["league_id"])
    @league_race = LeagueRace.new
  end
  
  # GET /league_races/1/edit
  def edit
  end
  
  # POST /league_races or /league_races.json
  def create
    @league_race = LeagueRace.new(league_race_params)
    @points_for_position = PointsForPosition.where(score_system_id: (params.dig(:league_race, :score_system_id).to_i))
    @league_race.race_participants.each do |participant|
      if participant.position.to_i > 20
        participant.score = 0
      else
        participant.score = @points_for_position.find_by(position: participant.position.to_i).points
      end
    end
    
    respond_to do |format|
      if @league_race.save
        UpdateLeagueParticipantScore.call(@league_race)
        UpdateLeagueParticipantPosition.call(@league_race)
        format.html { redirect_to race_participants_path(league_race_id: @league_race.id), notice: "Carrera creada correctamente" }
        format.json { render :show, status: :created, location: @league_race }
      else
        format.html { redirect_to race_participants_path(league_race_id: @league_race.id), notice: "No se creó la carrera" }
        format.json { render json: @league_race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /league_races/1 or /league_races/1.json
  def update
    respond_to do |format|
      if @league_race.update(league_race_params)
        format.html { redirect_to league_race_url(@league_race), notice: "League race was successfully updated." }
        format.json { render :show, status: :ok, location: @league_race }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @league_race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /league_races/1 or /league_races/1.json
  def destroy
    @league_race.destroy

    respond_to do |format|
      format.html { redirect_to league_races_url, notice: "League race was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def score_for_position(score_system)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league_race
      @league_race = LeagueRace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def league_race_params
      params.require(:league_race)
            .permit(
                    :name,
                    :description,
                    :race_track_id,
                    :league_id,
                    :score_system_id,
                    race_participants_attributes: [
                                                    :id,
                                                    :user_id,
                                                    :race_league_id,
                                                    :position,
                                                    :score,
                                                    :status,
                                                    :_destroy]
                    )
    end
end

app/helpers/league_races_helper.rb
module LeagueRacesHelper
end

app/views/league_races/_form.html.erb
<%= simple_form_for(@league_race) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs col-md-6">
    <%= f.association :league, as: :hidden,
                               input_html: { class: 'form-control mb-2', value: @league.id } %>
    <%= f.input :name, input_html: { class: 'form-control mb-2' } %>
    <%= f.input :description, input_html: { class: 'form-control mb-2' } %>
    <%= f.association :race_track, collection: RaceTrack.order(:name),
                                   prompt: 'Seleccione una pista',
                                   input_html: { class: 'form-control mb-2' } %>
    <%= f.association :score_system, as: :radio_buttons, label: 'Sistema de puntaje' %>
    <br>
    <h4>Participantes</h4>
    <%= f.fields_for :race_participants do |race_participant| %>
      <%= render 'race_participant_fields', f: race_participant %>
    <% end %>

    <div class="link">
      <%= link_to_add_association "Agregar otro participante", f, :race_participants %>
    </div>
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit, 'Crear nueva carrera', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/league_races/_race_participant_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <div class="col-md-6">
      <%= f.input :user_id, collection: User.from_this_league(@league.id).order(:gamer_id),
                                  prompt: 'Seleccione un usuario',
                                  input_html: { class: 'form-control d-inline-block' } %>
      <%= f.input :position, collection: f1_race_positions,
                                  prompt: 'Seleccione una posición',
                                  input_html: { class: 'form-control mb-2 d-inline-block' } %>
      <%= f.input :score, as: :hidden %>
      <br>
      <%= link_to_remove_association "Remover participante", f %>
    </div>
  </div>
</div>

app/views/league_races/edit.html.erb
<h1>Editing League Race</h1>

<%= render 'form', league_race: @league_race %>

<%= link_to 'Show', @league_race %> |
<%= link_to 'Back', league_races_path %>

app/views/league_races/index.html.erb
<p id="notice"><%= notice %></p>

<div class='col-md-6'>
  <h1>Carreras de <strong><%= @league&.name %></strong></h1>
</div>

<%= link_to 'Crear nueva carrera', new_league_race_path(league_id: @league.id) %>
<br>
<% @league_races.each do |league_race| %>
  <div class="card col-md-6 mt-2">
    <div class="card-body">
      <h4 class="card-title"><%= league_race.capitalized_name %></h4>
      <p class="card-text">Descripción: <%= league_race.description %></p>
      <p class="card-text">Pista: <strong><%= league_race.race_track.name %></strong></p>
      <a href="<%= score_system_path(league_race.score_system_id)%>">Sistema de puntaje</a>
      <br>
      <a href="<%= race_participants_path(league_race_id: league_race.id) %>" class="btn btn-dark">Ver tabla de resultados</a>
      <a href="<%= sanctions_path(league_race_id: league_race.id) %>" class="btn btn-dark">Ver sanciones</a>
      <a href="<%= bonus_points_path(league_race_id: league_race.id) %>" class="btn btn-dark">Ver puntos extra</a>
    </div>
  </div>
<% end %>

app/views/league_races/new.html.erb
<div class='col-md-6'>
  <h1>Crear nueva carrera de <strong><%= @league.capitalized_name %></strong></h1>
</div>

<%= render 'form', league_race: @league_race %>
<br>
<%= link_to 'Volver a listado de carreras', league_races_path(league_id: @league.id) %>

app/views/league_races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @league_race.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @league_race.description %>
</p>

<p>
  <strong>Race track:</strong>
  <%= @league_race.race_track_id %>
</p>

<p>
  <strong>League:</strong>
  <%= @league_race.league_id %>
</p>

<%= link_to 'Edit', edit_league_race_path(@league_race) %> |
<%= link_to 'Back', league_races_path(league_id: @league_race.league.id) %>