config/routes.rb
Rails.application.routes.draw do
  resources :bonus_points
  resources :sanctions
  resources :league_participants
  resources :race_participants
  devise_for :users
  resources :league_races
  resources :race_tracks
  resources :leagues
  resources :points_for_positions
  resources :score_systems

  root to: "leagues#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/race_participant.rb
class RaceParticipant < ApplicationRecord
  belongs_to :user
  belongs_to :league_race
  has_many :sanctions
  has_many :bonus_points

  scope :from_league_race, -> (league_race) { where(league_race_id: league_race) }

  def sanction_points
    sanctions.pluck(:penalized_points).compact.sum
  end

  def total_race_points
    score - sanction_points
  end
end

app/controllers/race_participants_controller.rb
class RaceParticipantsController < ApplicationController
  before_action :set_race_participant, only: %i[ show edit update destroy ]

  # GET /race_participants or /race_participants.json
  def index
    @league_race = LeagueRace.find(params["league_race_id"])
    @race_participants = RaceParticipant.from_league_race(@league_race.id).order('score DESC, position')
  end

  # GET /race_participants/1 or /race_participants/1.json
  def show
  end

  # GET /race_participants/new
  def new
    @race_participant = RaceParticipant.new
  end

  # GET /race_participants/1/edit
  def edit
  end

  # POST /race_participants or /race_participants.json
  def create
    @race_participant = RaceParticipant.new(race_participant_params)

    respond_to do |format|
      if @race_participant.save
        format.html { redirect_to race_participant_url(@race_participant), notice: "Race participant was successfully created." }
        format.json { render :show, status: :created, location: @race_participant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @race_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /race_participants/1 or /race_participants/1.json
  def update
    respond_to do |format|
      if @race_participant.update(race_participant_params)
        format.html { redirect_to race_participant_url(@race_participant), notice: "Race participant was successfully updated." }
        format.json { render :show, status: :ok, location: @race_participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @race_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /race_participants/1 or /race_participants/1.json
  def destroy
    @race_participant.destroy

    respond_to do |format|
      format.html { redirect_to race_participants_url, notice: "Race participant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race_participant
      @race_participant = RaceParticipant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def race_participant_params
      params.require(:race_participant).permit(:user_id, :status, :position, :score, :league_race_id)
    end
end

app/helpers/race_participants_helper.rb
module RaceParticipantsHelper
end

app/views/race_participants/_form.html.erb
<%= simple_form_for(@race_participant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :status %>
    <%= f.input :position %>
    <%= f.input :score %>
    <%= f.association :league_race %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/race_participants/edit.html.erb
<h1>Editing Race Participant</h1>

<%= render 'form', race_participant: @race_participant %>

<%= link_to 'Show', @race_participant %> |
<%= link_to 'Back', race_participants_path %>

app/views/race_participants/index.html.erb
<p id="notice"><%= notice %></p>

<div class='col-md-6'>
  <h1>Participantes de la carrera: <strong><%= @league_race.capitalized_name %></strong></h1>
</div>

<div class='col-md-7'>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id de jugador</th>
        <th scope="col">Posición</th>
        <th scope="col">Puntaje preliminar</th>
        <th scope="col">Puntos de penalización</th>
        <th scope="col">Puntaje final</th>
      </tr>
    </thead>
    <tbody>
      <% @race_participants.each do |race_participant| %>
        <tr>
          <td><%= race_participant.user.gamer_id %></td>
          <td><%= race_participant.position.to_i > 20 ? 'DNF' : race_participant.position %></td>
          <td><%= race_participant.score %></td>
          <td>-<%= race_participant.sanction_points %></td>
          <td><%= race_participant.total_race_points %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<a href="<%= league_races_path(league_id: @league_race.league_id) %>" class="btn btn-dark">Volver a carreras de liga</a>
<a href="<%= league_participants_path(league_id: @league_race.league_id) %>" class="btn btn-dark">Ir a tabla general de la liga</a>
<a href="<%= sanctions_path(league_race_id: @league_race.id) %>" class="btn btn-dark">Ver sanciones</a>

app/views/race_participants/new.html.erb
<h1>New Race Participant</h1>

<%= render 'form', race_participant: @race_participant %>

<%= link_to 'Back', race_participants_path %>

app/views/race_participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @race_participant.user_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @race_participant.status %>
</p>

<p>
  <strong>Position:</strong>
  <%= @race_participant.position %>
</p>

<p>
  <strong>Score:</strong>
  <%= @race_participant.score %>
</p>

<p>
  <strong>League race:</strong>
  <%= @race_participant.league_race_id %>
</p>

<%= link_to 'Edit', edit_race_participant_path(@race_participant) %> |
<%= link_to 'Back', race_participants_path %>